package tofu

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/queuezero/queuezero/internal/spec"
)

// FoundationOpts names the resources the cluster-foundation layer creates. These
// are exactly the substrate the elastic-fleet runtime (phases 2c-2e) already
// assumes: an IAM instance profile the bootstrap shim runs under, and the S3
// buckets the uploader and manifest publisher write to.
type FoundationOpts struct {
	ScriptsBucket  string // q0:bootstrap-s3 / Q0_SCRIPTS_BUCKET target
	ManifestBucket string // Q0_MANIFEST_BUCKET target (collective peer manifests)
	NodeRoleName   string // IAM role + instance profile name (e.g. "q0-node"); default applied if empty
}

const defaultNodeRole = "q0-node"

// GenerateClusterFoundation renders the .tf files for the foundation layer and
// returns them as filename->content (also written to dir). It does NOT run tofu;
// the caller applies them via an Executor. The generated HCL is deterministic so
// it is golden-file testable and produces stable plans.
func GenerateClusterFoundation(c *spec.Cluster, opts FoundationOpts) (map[string]string, error) {
	if c == nil {
		return nil, fmt.Errorf("tofu: nil cluster")
	}
	if opts.ScriptsBucket == "" {
		return nil, fmt.Errorf("tofu: ScriptsBucket is required (the bootstrap shim fetches from it)")
	}
	if opts.NodeRoleName == "" {
		opts.NodeRoleName = defaultNodeRole
	}
	data := struct {
		Region         string
		ScriptsBucket  string
		ManifestBucket string
		NodeRole       string
	}{c.Region, opts.ScriptsBucket, opts.ManifestBucket, opts.NodeRoleName}

	files := map[string]string{}
	for name, tmpl := range foundationTemplates {
		var b strings.Builder
		if err := tmpl.Execute(&b, data); err != nil {
			return nil, fmt.Errorf("tofu: render %s: %w", name, err)
		}
		files[name] = b.String()
	}
	return files, nil
}

// WriteFiles persists rendered HCL into dir, creating it if needed.
func WriteFiles(dir string, files map[string]string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("tofu: mkdir %s: %w", dir, err)
	}
	names := make([]string, 0, len(files))
	for n := range files {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		if err := os.WriteFile(filepath.Join(dir, n), []byte(files[n]), 0o644); err != nil {
			return fmt.Errorf("tofu: write %s: %w", n, err)
		}
	}
	return nil
}

var foundationTemplates = map[string]*template.Template{
	"main.tf":      template.Must(template.New("main").Parse(mainTF)),
	"variables.tf": template.Must(template.New("vars").Parse(variablesTF)),
	"outputs.tf":   template.Must(template.New("out").Parse(outputsTF)),
}

const mainTF = `# GENERATED by q0 apply — do not edit by hand. Edit cluster.yaml and re-apply.
terraform {
  backend "s3" {}
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "{{.Region}}"
}

# --- Bootstrap script-set bucket (q0 bootstrap push target; shim fetches from here) ---
resource "aws_s3_bucket" "scripts" {
  bucket = "{{.ScriptsBucket}}"
}

resource "aws_s3_bucket_versioning" "scripts" {
  bucket = aws_s3_bucket.scripts.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_public_access_block" "scripts" {
  bucket                  = aws_s3_bucket.scripts.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
{{if .ManifestBucket}}
# --- Collective peer-manifest bucket (cohort assembler publishes here) ---
resource "aws_s3_bucket" "manifest" {
  bucket = "{{.ManifestBucket}}"
}

resource "aws_s3_bucket_public_access_block" "manifest" {
  bucket                  = aws_s3_bucket.manifest.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
{{end}}
# --- Node IAM role + instance profile (the bootstrap shim runs under this) ---
resource "aws_iam_role" "node" {
  name = "{{.NodeRole}}"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "ec2.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

# Scoped to GetObject on the scripts bucket only — least privilege for the shim.
resource "aws_iam_role_policy" "node_scripts_read" {
  name = "{{.NodeRole}}-scripts-read"
  role = aws_iam_role.node.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = ["s3:GetObject"]
      Resource = "${aws_s3_bucket.scripts.arn}/*"
    }]
  })
}

resource "aws_iam_instance_profile" "node" {
  name = "{{.NodeRole}}"
  role = aws_iam_role.node.name
}
`

const variablesTF = `# GENERATED by q0 apply — do not edit by hand.
# The foundation layer takes no input variables; all values are rendered from
# cluster.yaml at generation time. Backend values are supplied via
# -backend-config at init.
`

const outputsTF = `# GENERATED by q0 apply — do not edit by hand.
output "node_instance_profile_arn" {
  value       = aws_iam_instance_profile.node.arn
  description = "Set Q0_INSTANCE_PROFILE_ARN to this for q0-resume."
}

output "scripts_bucket" {
  value       = aws_s3_bucket.scripts.id
  description = "Set Q0_SCRIPTS_BUCKET to this for q0 bootstrap push."
}
{{if .ManifestBucket}}
output "manifest_bucket" {
  value       = aws_s3_bucket.manifest.id
  description = "Set Q0_MANIFEST_BUCKET to this for collective resume."
}
{{end}}`
